### ISSUE TITLE
Error Loading Test Results

### ISSUE THREAD

**Issue by Sweetdevil144** [PecanProject/pecan-status-board#13]
After setting up `pecan-status-board`, I tried running the app on my RStudio Platform. However, I've been facing some server errors with following error logs displayed while the screen stays over in loading scenario.

*Command :*

```r
statusboard::run_app()
Loading required package: shiny
```

*Logs :*

```
Listening on http://127.0.0.1:6219
The `name` provided ('clock-o') does not correspond to a known icon
The `name` provided ('square-s') does not correspond to a known icon
The `name` provided ('square-e') does not correspond to a known icon
The `name` provided ('square-C') does not correspond to a known icon
Sorry! Server not responding.
Sorry! Server not responding.
Sorry! Server not responding.
Sorry! Server not responding.
```

**Comment by mdietze** [comment]
I think this is related to changes in the underlying libraries over the last couple years. See this post for discussion and possible solutions: https://stackoverflow.com/questions/32686195/shinydashboard-some-font-awesome-icons-not-working

@Sweetdevil144   If you get things working, please submit a pull request with your updates

**Comment by Sweetdevil144** [comment]
Thanks for the suggestions @mdietze . I'll check out the above link and remind you of the progress on the same.

**Comment by Sweetdevil144** [comment]
Hey,
Sorry for the late response on this issue.
I found the `fontawesome` R package (https://github.com/rstudio/fontawesome), which could fix our icon issues in the Pecan Status Board. It offers updated icons and better Shiny compatibility. Might be worth a try for a smoother integration.
Any suggestions @mdietze ?

**Comment by mdietze** [comment]
Yeah, give it a try. If it works submit a PR.

**Comment by Sweetdevil144** [comment]
Update on errors : 

- I replaced `icon("clock",verify_fa=FALSE)` with `icon("clock",lib="font-awesome")` at all instances wherever the error was indicated.
- Commited the changes to my `main` branch

**Following error logs were displayed**

```R
Browsing http://127.0.0.1:5071
The `name` provided ('clock-o') does not correspond to a known icon
The `name` provided ('square-s') does not correspond to a known icon
The `name` provided ('square-e') does not correspond to a known icon
The `name` provided ('square-C') does not correspond to a known icon
Sorry! Server not responding.
Sorry! Server not responding.
Warning: Error in : id variables not found in data: Workflow_id
  52: stop
  51: melt_check
  50: melt.data.frame
  48: module
  43: callModule
  42: moduleServer
  41: mod_workflows_satus_server
  40: server
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Error : id variables not found in data: Workflow_id
```

+ Although I changed my `square-s` to simple `square` combined with `lib=font-awesome`, yet these old logs were displayed.
+ New **WARNING** logs noticed. Notice the stack calls made which start from either `R/app_server.R` OR `R/mod_workflows_status.R`.

Opening the PR related to same

**Comment by Sweetdevil144** [comment]
For the Second (New) error logs, I wanted to clear two more things : 
- Should I create a new Issue corresponding to the same?
- Should I add some custom test cases/assert statements to pinpoint the source of this error?
