### ISSUE TITLE
Feature : Issue and Pull Request Templates

### ISSUE THREAD

**Issue by Sweetdevil144** [PecanProject/pecan-status-board#18]
Maybe we can add an Issue and a Pull Request template just as one utilized in the main `PEcAn` repository. Different templates for Bug Reports, Feature Requests, Code changes or Documentation changes ?

**Comment by Sweetdevil144** [comment]
Should we proceed with adding this feature? Any suggestions @infotroph and @mdietze . We simply can copy the `ISSUE_TEMPLATE` from the `PEcAn` repository.

**Comment by mdietze** [comment]
@Sweetdevil144 this is not a high priority item for me, but it's a good suggestion and I'm fine with you implementing it 👍
